steps:
#This step builds the container image
  - name: "gcr.io/cloud-builders/docker"
    id: Build
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/lesliee-cruz-stedi:latest"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    id: Push
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/lesliee-cruz-stedi:latest"
  - name: "gcr.io/cloud-builders/docker"
    id: Test
    args:
      - "run"
      - "gcr.io/$PROJECT_ID/lesliee-cruz-stedi:latest"
